/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Modelos.Jugador;
import java.awt.Color;
import java.awt.Font;
import java.util.Collections;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import juegomecanografia.Archivo;

/**
 *
 * @author Dalex
 */
public class VisPodio extends javax.swing.JFrame {

    Archivo archivos = new Archivo();
    int Xmov, Ymov;
    int tiempoJuego, dificultad;
    final int PUNTOS_POR_ACIERTO = 10;
    final int PUNTOS_POR_FALLOS = 10;
    final int PUNTOS_POR_TIEMPO = 2;
    LinkedList<Jugador> listaJugadores;

    /**
     * Creates new form VisGanador
     */
    public VisPodio() {
        initComponents();
        this.setLocationRelativeTo(this);
        estilosArcade();
        cargarJugadores();
        llenartabla();
        mostrarGanadores();
        cambiarAnchoCeldas();

    }

    private void cargarJugadores() {
        this.listaJugadores = this.archivos.extraer("jugadores.txt");
        DefaultTableModel modeloTabla = new DefaultTableModel(new Object[]{"NOMBRE", "ACIERTOS", "FALLOS", "TIEMPO", "Pun. ACIERTOS",
            "Pun. FALLOS", "Pun. TIEMPO", "PUNTAJE"}, this.listaJugadores.size());
        this.jtblPodio.setModel(modeloTabla);
        Collections.sort(listaJugadores);
    }

    private void estilosArcade() {
        jLabel1.setFont(new Font("ARCADECLASSIC", Font.PLAIN, 45)); // Ajusta el tamaño y el estilo según sea necesario
        jlblTercerLugar.setFont(new Font("ARCADECLASSIC", Font.PLAIN, 40));
        jlblSegundoLugar.setFont(new Font("ARCADECLASSIC", Font.PLAIN, 40));
        jlblPrimerLugar.setFont(new Font("ARCADECLASSIC", Font.PLAIN, 40));
        jbtnInicio.setFont(new Font("ARCADECLASSIC", Font.PLAIN, 24));
        jbtnBorrarDatos.setFont(new Font("ARCADECLASSIC", Font.PLAIN, 24));
    }

    private void cambiarAnchoCeldas() {
        for (int i = 0; i < this.jtblPodio.getRowCount(); i++) {
            this.jtblPodio.setRowHeight(i, 55);
        }
    }

    private void llenartabla() {
        for (int i = 0; i < this.listaJugadores.size(); i++) {
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).nombre, i, 0);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).aciertos, i, 1);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).fallos, i, 2);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).tiempoRestante, i, 3);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).punAciertos, i, 4);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).puntFallos, i, 5);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).punTiempo, i, 6);
            this.jtblPodio.setValueAt(this.listaJugadores.get(i).resultado, i, 7);
        }
    }

    private void mostrarGanadores() {
        jlblPrimerLugar.setText("Sin lugar");
        jlblSegundoLugar.setText("Sin lugar");
        jlblTercerLugar.setText("Sin lugar");

        for (int i = 0; i < listaJugadores.size(); i++) {
            Jugador jugador = listaJugadores.get(i);
            switch (i) {
                case 0 ->
                    jlblPrimerLugar.setText(jugador.nombre);
                case 1 ->
                    jlblSegundoLugar.setText(jugador.nombre);
                case 2 ->
                    jlblTercerLugar.setText(jugador.nombre);
                default -> {
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPodio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlblPrimerLugar = new javax.swing.JLabel();
        jlblTercerLugar = new javax.swing.JLabel();
        jlblSegundoLugar = new javax.swing.JLabel();
        jbtnBorrarDatos = new javax.swing.JButton();
        jbtnInicio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPnl_salida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPnl_min = new javax.swing.JPanel();
        jLbl_min = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblPodio.setBackground(new java.awt.Color(204, 204, 204));
        jtblPodio.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtblPodio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPodio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 920, 190));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jlblPrimerLugar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlblPrimerLugar.setForeground(new java.awt.Color(255, 255, 255));
        jlblPrimerLugar.setText("primero");
        jPanel1.add(jlblPrimerLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        jlblTercerLugar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlblTercerLugar.setForeground(new java.awt.Color(255, 255, 255));
        jlblTercerLugar.setText("tercerdo");
        jPanel1.add(jlblTercerLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 220, 50));

        jlblSegundoLugar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlblSegundoLugar.setForeground(new java.awt.Color(255, 255, 255));
        jlblSegundoLugar.setText("segundo");
        jPanel1.add(jlblSegundoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jbtnBorrarDatos.setBackground(new java.awt.Color(255, 0, 51));
        jbtnBorrarDatos.setText("borrar datos");
        jbtnBorrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBorrarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBorrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 200, 60));

        jbtnInicio.setBackground(new java.awt.Color(51, 255, 0));
        jbtnInicio.setText("Inicio");
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(530, 420));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnl_salida.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPnl_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnl_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnl_salidaMouseExited(evt);
            }
        });
        jPnl_salida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("   X");
        jPnl_salida.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel3.add(jPnl_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 50, 30));

        jPnl_min.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPnl_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnl_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnl_minMouseExited(evt);
            }
        });
        jPnl_min.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbl_min.setBackground(new java.awt.Color(0, 0, 0));
        jLbl_min.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLbl_min.setText("   -");
        jPnl_min.add(jLbl_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel3.add(jPnl_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 50, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logojuego.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 210, 180));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logojuego.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPnl_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_salidaMouseClicked

        int mensaje = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "Confirmación de salida", JOptionPane.YES_NO_OPTION);

        if (mensaje == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jPnl_salidaMouseClicked

    private void jPnl_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_salidaMouseEntered
        jPnl_salida.setBackground(Color.red);
    }//GEN-LAST:event_jPnl_salidaMouseEntered

    private void jPnl_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_salidaMouseExited
        jPnl_salida.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPnl_salidaMouseExited

    private void jPnl_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_minMouseClicked
        setExtendedState(JFrame.ICONIFIED);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPnl_minMouseClicked

    private void jPnl_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_minMouseEntered
        jPnl_min.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jPnl_minMouseEntered

    private void jPnl_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_minMouseExited
        jPnl_min.setBackground(Color.white);
    }//GEN-LAST:event_jPnl_minMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Xmov, y - Ymov);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        Xmov = evt.getX();
        Ymov = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed

        VistaInicio visIn = new VistaInicio();
        visIn.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jbtnBorrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarDatosActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar\n todos los datos de los jugadores?", "Confirmación de salida", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            archivos.borrar("jugadores.txt");
            JOptionPane.showMessageDialog(null, "Se ha eliminado todas los datos");
             VistaInicio visIn = new VistaInicio();
        visIn.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jbtnBorrarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisPodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisPodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisPodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisPodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisPodio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbl_min;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnl_min;
    public javax.swing.JPanel jPnl_salida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBorrarDatos;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JLabel jlblPrimerLugar;
    private javax.swing.JLabel jlblSegundoLugar;
    private javax.swing.JLabel jlblTercerLugar;
    private javax.swing.JTable jtblPodio;
    // End of variables declaration//GEN-END:variables
}
